language: node_js
node_js:
  - 6
  - 8
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
script:
  # Run test script
  - "yarn run lint"
  - "yarn test -- --maxWorkers=4"
  - "scripts/is-it-pretty.sh"
after_script:
  - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
